### ISSUE TITLE
How to run in cli mode?

### ISSUE THREAD

**Issue by kovetskiy** [palantir/palantir-java-format#57]
Hi, I'd like to thank you for such valuable project, it is really awesome.

google-java-format can be started as a usual binary program without any IDE/gradle plugins, you just run in console `google-java-format <filename>` and it modifies file, can I do something like that with palatir-java-format?

I tried to run it by specifying Main class but got an exception
```
/usr/bin/java -cp palantir-java-format-0.3.0.jar com.palantir.javaformat.java.Main
Error: Unable to initialize main class com.palantir.javaformat.java.Main
Caused by: java.lang.NoClassDefFoundError: com/palantir/javaformat/java/FormatterException
```

Actually, there is no FormatterException but there is FormatterException**s**
```
 ∞ unzip -l palantir-java-format-0.3.0.jar # FormatterException
     2544  1980-02-01 00:00   com/palantir/javaformat/java/FormatterExceptions.class
```

**Comment by dansanduleac** [comment]
Hi @kovetskiy, thanks for the issue!

The main issue here is that you need more than just that jar to run the cli - we've separated some of the classes into a separate jar in order to facilitate an SPI / implementation split, such that the intellij plugin can work with any version without requiring a reinstall (and an IntelliJ restart as a result). So you also need `palantir-java-format-spi-{version}.jar` on the classpath.
Perhaps it might make sense to publish a shadow jar for that purpose?

Also, note that there's currently no way to run the CLI in the PALANTIR style (120 chars, 4 space indent)..  This is not hard to add but we just didn't wire this up yet because we don't run the cli internally (we run it either from gradle via the plugin `com.palantir.baseline-format`, or from intellij via the intellij plugin).

**Comment by kovetskiy** [comment]
Thanks! I've also figured out that it needs to have google-java-format's jar in the classpath because it uses various `com.google.*` dependencies.

It would be cool to have `palantir-java-format-all-deps.jar` like google-java-format does: https://github.com/google/google-java-format#from-the-command-line

Currently, I'm running it like as following (I've created a package for Arch Linux users):
https://aur.archlinux.org/cgit/aur.git/tree/palantir-java-format?h=palantir-java-format

package source files: https://aur.archlinux.org/cgit/aur.git/tree/?h=palantir-java-format
package page: https://aur.archlinux.org/packages/palantir-java-format/

**Comment by xjrga** [comment]
> palantir-java-format-all-deps.jar

I like the formatting. I am also looking for that jar file.

**Comment by abashev** [comment]
If anybody come here as me to find all-deps jar then there is solution for git hooks and so on - palantir is releasing native binaries that could be used as part of builds

```
FORMATTER_VERSION="2.89.0"
CACHE_DIR="${HOME}/.cache/palantir-java-format"
BINARY="${CACHE_DIR}/palantir-java-format-${FORMATTER_VERSION}"
BASE_URL="https://repo1.maven.org/maven2/com/palantir/javaformat/palantir-java-format-native/${FORMATTER_VERSION}"

.....

# Download native binary if not cached
if [ ! -x "$BINARY" ]; then
    OS=$(uname -s)
    ARCH=$(uname -m)

    case "${OS}-${ARCH}" in
        Linux-x86_64)  SUFFIX="linux-glibc_x86-64" ;;
        Linux-aarch64) SUFFIX="linux-glibc_aarch64" ;;
        Darwin-arm64)  SUFFIX="macos_aarch64" ;;
        *)
            echo "ERROR: No palantir-java-format native binary for ${OS}-${ARCH}."
            echo "       Supported: Linux x86_64, Linux aarch64, macOS aarch64."
            exit 1
            ;;
    esac

    ARTIFACT="palantir-java-format-native-${FORMATTER_VERSION}-nativeImage-${SUFFIX}.bin"
    DOWNLOAD_URL="${BASE_URL}/${ARTIFACT}"

    echo "Downloading palantir-java-format ${FORMATTER_VERSION} (${SUFFIX})..."
    mkdir -p "$CACHE_DIR"

    if ! curl -sSfL -o "$BINARY" "$DOWNLOAD_URL"; then
        rm -f "$BINARY"
        echo "ERROR: Failed to download palantir-java-format from:"
        echo "       $DOWNLOAD_URL"
        exit 1
    fi

    chmod +x "$BINARY"
fi
