### ISSUE TITLE
Is there a documented set of rules?

### ISSUE THREAD

**Issue by jo2** [palantir/palantir-java-format#829]
We're evaluating if using palantir java format is the right formatter for our project. Is there an overview over all rules in the palantir java format?

**Comment by iamdanfox** [comment]
palantir-java-format doesn't have 'rules' available to tune - it's intentionally a **non-configurable formatter**. 

The README has a couple of illustrative examples https://github.com/palantir/palantir-java-format#motivation--examples, but I think the best way to decide if it would be net positive for your project to adopt would be to just try formatting your codebase and see what you think of the output. You can then weigh the pros and cons (see https://github.com/palantir/palantir-java-format#upsides-of-automatic-formatting and https://github.com/palantir/palantir-java-format#downsides-of-automatic-formatting).

**Comment by jo2** [comment]
For us it would be interesting to have the set of rules, that are to be followed to be compliant to palantir code style, so that our team members can know, which rules are there and don't have to guess if their project will build or not.

Also we could use this rule set for an in depth comparison between our current formatting rule set and the palantir rule set. Our first impression is, that palantir would me more suited for us, but for a final decision we'd like to make a full comparison, because I'm sure that the code samples we've tried the palantir formatter on do not cover any rule there is.

**Comment by iamdanfox** [comment]
> team members can know, which rules are there and don't have to guess if their project will build or not.

Nobody should have to 'guess' if their project will build or not. Instead the workflow I'd recommend is:

1. While writing code, use the IntelliJ plugin to format your code on save. Formatting is pretty much instantaneous, so you can just let it overwrite whatever you have typed. You should never manually edit whitespace to try to 'conform' to palantir-java-format's opinions, you should just run the formatter!
2. In CI, you should run palantir-java-format in 'validation' mode. This is done by applying the `com.diffplug.spotless` plugin, which should be automatically configured by the `com.palantir.java-format` plugin. This will fail the build if anything is not formatted correctly.

**Comment by jo2** [comment]
It is already planned to use the formattter in combination with spotless in our pipelines. Those of us who use IntelliJ won't have any problem with that, sadly some of us are still using Eclipse, so this workflow won't work for them. Our plan was to write a formatting configuration file for eclipse based on the rules used in the palantir formatter.

**Comment by iamdanfox** [comment]
> write a formatting configuration file for eclipse based on the rules used in the palantir formatter.

I would caution against this, as I think it would lead to quite a lot of developer frustration. Specifically the big benefit for a formatter we found was if _everyone_ uses the same formatter, then arguments and friction goes down a lot. If I was an eclipse-using member of the team, I think I'd find it frustrating to run the eclipse formatter if it makes a bunch of whitespace changes that I have to later fix up to satisfy palantir-java-format (either in CI, or by running a second command line arg). Also note that the reason we built palantir-java-format is because the code formatting style we wanted was _not_ achievable with eclipse formatter ([we did try](https://github.com/palantir/gradle-baseline/blob/develop/gradle-baseline-java-config/resources/spotless/eclipse.xml)).

Note that in the original google-java-format codebase we forked, there was an eclipse plugin (https://github.com/palantir/palantir-java-format/tree/develop/eclipse_plugin) - we just didn't invest in this because at Palantir 99% of developers use IntelliJ. I'd defer to current maintainers if they'd accept contributions to this eclipse plugin, if you wanted to try to make that work?

**Comment by jo2** [comment]
ok, thanks for the information and your help. We'll try the using the eclipse plugin, and as a fallback we can use the eclipse formatter setting and check the differences. Of course we'll put out a warning about the eclipse settings not being 100% accurate.
