### ISSUE TITLE
Palantir Java Format IntelliJ plugin version 2.29.0 not published to marketplace

### ISSUE THREAD

**Issue by mnazbro** [palantir/palantir-java-format#868]
The latest Palantir java format plugin is 2.29.0, but the most recent one is in the jetbrains plugin marketplace is 2.28.0. See https://plugins.jetbrains.com/plugin/13180-palantir-java-format/versions

Can we get the most recent version published since it fixes a save action problem?

**Comment by fawind** [comment]
Thanks for the flag! I believe this is because the publish token was outdated ([error message](https://app.circleci.com/pipelines/github/palantir/palantir-java-format/2552/workflows/f328b415-e80f-4370-8446-ea238a353b15/jobs/13784)). I updated the token and triggered a new release, [2.30.0](https://github.com/palantir/palantir-java-format/releases/tag/2.30.0). Let's see if that goes through!

**Comment by fawind** [comment]
Looks like the release went through and is currently going through the Jetbrains review but should be available soon!
