### ISSUE TITLE
palantir-java-format 2.37.0 is not available in Maven Central

### ISSUE THREAD

**Issue by rpalcolea** [palantir/palantir-java-format#927]
Hi folks,

We saw that 2.37.0 was released https://github.com/palantir/palantir-java-format/releases/tag/2.37.0 and it hit the gradle plugin portal properly -> https://plugins.gradle.org/plugin/com.palantir.java-format

However, it looks like libraries didn't make it to maven central:

* https://repo1.maven.org/maven2/com/palantir/javaformat/palantir-java-format-spi/
* https://repo1.maven.org/maven2/com/palantir/javaformat/palantir-java-format

Wondering if something went wrong in publishing or maven central is having issues serving this version in particular

**Comment by fawind** [comment]
Thanks for flagging!

It looks like the publishing circle job failed and didn't publish all artifacts: https://app.circleci.com/pipelines/github/palantir/palantir-java-format/2718/workflows/7c534779-8978-48bf-89cd-c542a7792d83/jobs/14111

I can take a look at this later and try to get a new (complete) release out.

**Comment by fawind** [comment]
I'm not 100% sure, but I believe this was due to a flake from sonatype (which is used as a staging repo for maven central ([details](https://github.com/palantir/gradle-external-publish-plugin#publishing-to-maven-central)).

I have re-run the job and it seemed to have published the missing 2.37.0 artifacts and also triggered a full new release ([2.38.0](https://github.com/palantir/palantir-java-format/releases/tag/2.38.0)), which seemed to have gone through: https://repo1.maven.org/maven2/com/palantir/javaformat/palantir-java-format-spi/2.38.0/

Closing for now, but lmk if there are more issues!
